name: Build Python Azure Function

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
      BUILD_PATH:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
      CURRENT_BRANCH:
        required: true
        type: string
        default: ${{ github.ref }}

jobs:
  build:
    name: Build Azure Function
    runs-on: ubuntu-latest
    defaults:
      run:
        # Working directory for all 'run' steps
        working-directory: ${{ inputs.BUILD_PATH }} 
    steps:
      - name: Checkout ${{ inputs.CURRENT_BRANCH }} 
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.CURRENT_BRANCH }}

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi

      - name: Run linter tests
        run: |
          pytest --flake8 -m flake8 --cache-clear .

      - name: Run unit tests
        run: |
          python -m pytest tests/ --cov --cov-report xml:coverage.xml --cov-config=.coveragerc

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: |
            . 
            !venv/
