name: Terraform Build (init/plan)

on:
  workflow_call:
      inputs:
        python_version:
          required: true
          type: string
      secrets:
        TF_BACKEND_RG: 
          required: true
        TF_BACKEND_SA:
          required: true
        TF_BACKEND_CONTAINER_NAME:
          required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_BACKEND_RG }}" \
                         -backend-config="storage_account_name=${{ secrets.TF_BACKEND_SA }}" \
                         -backend-config="container_name=${{ secrets.TF_BACKEND_CONTAINER_NAME }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color