name: Build Python Azure Function

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
      BUILD_PATH:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
      CURRENT_BRANCH:
        required: true
        type: string
        default: ${{ github.ref }}
env:
  OUTPUT_DIR: output
  ZIP_FILE_NAME: ${{ inputs.ARTIFACT_NAME }}.zip

jobs:
  build_tests:
    name: Run tests and install requirements
    uses: qurixtechnology/base-workflows/.github/workflows/build_python_tests.yml@feature/reuse-python-tests
    with:
      python_version: ${{ inputs.PYTHON_VERSION }}
      root_path:  ${{ inputs.BUILD_PATH }}
      current_branch: ${{ github.current_branch }}
      test_dir: tests
      venv_name: .venv
      ignore_pep8: ""

  upload:
    name: Upload Azure Function artifact
    runs-on: ubuntu-latest

    defaults:
      run:
        # Working directory for all 'run' steps
        working-directory: ${{ inputs.BUILD_PATH }}
    steps:      
      - name: Create package folder
        run: |
          mkdir ${{ env.OUTPUT_DIR }}
          zip -r ${{ env.OUTPUT_DIR }}/${{ env.ZIP_FILE_NAME }} .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: ${{ inputs.BUILD_PATH }}/${{ env.OUTPUT_DIR }}/${{ env.ZIP_FILE_NAME }}
          if-no-files-found: error
