name: Run Python Tests

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
      ROOT_PATH:
        description: 'Root directory of the Python'
        required: true
        type: string
        default: .
      CURRENT_BRANCH:
        required: true
        type: string
        default: ${{ github.ref }}
      TEST_DIR:
        description: 'Directory with tests (test_*.py) to run'
        required: true
        type: string
        default: tests
      VENV_NAME:
        description: 'Name of the virtual environment'
        required: true
        type: string
        default: .venv
      IGNORE_PEP8:
        description: 'Specific PEP8 guidelines that can be ignored, e.g.: E501,W191'
        required: true
        type: string
        default: ""

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
        
    defaults:
      run:
        # Working directory for all 'run' steps
        working-directory: ${{ inputs.ROOT_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python3 -m venv ${{ inputs.VENV_NAME }}
          source ${{ inputs.VENV_NAME }}/bin/activate
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --exclude ${{ inputs.VENV_NAME }},worker_venv,.python_packages --ignore=${{ inputs.IGNORE_PEP8 }}

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          python3 -m pytest ${{ inputs.TEST_DIR }} --cov --cov-report xml:coverage.xml --cov-config=.coveragerc
