name: Create Azure cost alert

on:
  workflow_call:
    inputs:
      AZURE_RG_NAME:
        required: true
        type: string
      AZURE_LOCATION:
        required: true
        type: string
      BUDGET:
        required: true
        type: string
      BUDGET_NAME:
        required: true
        type: string
      START_DATE:
        required: true
        type: string
      FIRST_THRESHOLD:
        required: false
        type: string
        default: "60"
      SECOND_THRESHOLD:
        required: false
        type: string
        default: "100"

    secrets:
      AZURE_CREDENTIALS:
        required: true

env:
  COST_ALERT_BICEP: ./bicep/cost_alert.bicep

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout bicep templates
        uses: actions/checkout@v3
        with:
          repository: qurixtechnology/base-workflows
          ref: feature/create-cost-alert
          path: .github/workflows
      - run: |
          az deployment group create \
          --resource-group ${{ inputs.AZURE_RG_NAME }} \
          --template-file  ./bicep/cost_alert.bicep \
          --parameters budgetName=${{ inputs.BUDGET_NAME }} \
                        amount=${{inputs.BUDGET}} \
                        timeGrain=Monthly \
                        startDate=${{ inputs.START_DATE}} \
                        firstThreshold=${{ inputs.FIRST_THRESHOLD }} \
                        secondThreshold=${{ inputs.SECOND_THRESHOLD}} \
                        contactEmails='("administration@qurix.tech",)' \
          --mode incremental
      - name: Summary
        run: |
          echo "### 💰 Budget created ${{ inputs.BUDGET_NAME }}: ${{ inputs.BUDGET}}" >> $GITHUB_STEP_SUMMARY