name: Deploy Python Azure Function

on:
  workflow_call:
    inputs:
      AZURE_FUNCTION_APP_NAME: 
        required: true
        type: string
      AZURE_FUNCTION_APP_BUILD_PATH:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
    
    secrets:
      AZURE_CREDENTIALS:
          required: true
      AZ_INGEST_FUNCTION_SETTINGS:
        required: true
      
jobs:
  deploy:
    name: Deploy Azure Function
    environment: ${{ inputs.ENVIRONMENT  }}
    
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: ${{ inputs.AZURE_FUNCTION_APP_BUILD_PATH }}

      - name: 'Deploy Azure Function'
        uses: azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.AZURE_FUNCTION_APP_NAME }}
          package: ${{ inputs.AZURE_FUNCTION_APP_BUILD_PATH }}/${{ inputs.ARTIFACT_NAME }}.zip
          scm-do-build-during-deployment: true
          enable-oryx-build: true
     
      - name: 'Sync App Settings'
        uses: azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ inputs.AZURE_FUNCTION_APP_NAME }} 
          app-settings-json: '${{ secrets.AZ_INGEST_FUNCTION_SETTINGS }}'
          mask-inputs: true
          #connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}' # <- in case of masked strings
          general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}'
      
      - name: 'WebApp URL'
        run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
      
      - name: 'Az cli logout'
        run: |
          az logout
