name: 'Deploy Azure Function (Python)'
on:
  workflow_call:
    inputs:
      AZURE_FUNCTION_APP_NAME: 
        required: true
        type: string
      PYTHON_VERSION:
        required: true
        type: string
      AZURE_FUNCTION_APP_BUILD_PATH:
        # it must be relative to the workflow dir
        required: true
        type: string
      ENVIRONMENT:
          required: true
          type: string
    
    secrets:
       AZURE_CREDENTIALS:
          required: true
      
jobs:
  deploy:
    name: Deploy Azure Function
    environment: ${{ inputs.ENVIRONMENT  }}

    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: 'Install dependencies'
        shell: bash
        run: |
          pushd './${{ inputs.AZURE_FUNCTION_APP_BUILD_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
      - name: 'Deploy Azure Function'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.AZURE_FUNCTION_APP_NAME }}
          package: ${{ inputs.AZURE_FUNCTION_APP_BUILD_PATH }}