name: Do Python Tests

on:
  workflow_call:
      inputs:
        python_version:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: ${{ input.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
      - name: Run linter tests
        run: |
          pytest --flake8 -m flake8 --cache-clear .
      - name: Run unit tests
        run: |
          python -m pytest tests/ --cov --cov-report xml:coverage.xml --cov-config=.coveragerc
