name: Validate Bicep File

on:
  workflow_call:
    inputs:
      BICEP_FILE_PATH:
        required: true
        type: string

jobs:
  validate:
    name: Validate file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Bicep file
        run: |
          az bicep build --file ${{ inputs.BICEP_FILE_PATH }}
